### ISSUE TITLE
Description references a different project

### ISSUE THREAD

**Issue by solidsnack** [manticore-projects/MJdbcUtils#3]
The description generated for Maven releases describes XMLDoclet, rather than this project.

https://github.com/manticore-projects/MJdbcUtils/blob/9c729cb7caf6a4fb5923f7b90c22bc7ffde201b6/build.gradle#L258

**Comment by manticore-projects** [comment]
Greetings!

Thank you for trying the software an reporting those issues. I believe to have fixed everything, however please never hesitate to report any findings or concerns.
Cheers!
